resolver: lts-15.0

packages:
- codegen
- libtorch-ffi
- hasktorch
- examples
- experimental

extra-include-dirs:
  - deps/libtorch/include/torch/csrc/api/include
  - deps/libtorch/include

extra-lib-dirs:
  - deps/libtorch/lib
  - deps/mklml/lib

# see https://github.com/commercialhaskell/stack/issues/4073
# with-gcc: /usr/local/bin/gcc-7

extra-deps:
- template-0.2.0.10@sha256:f822de4d34c45bc84b33a61bc112c15fedee6fa6dc414c62b10456395a868f85
- inline-c-cpp-0.4.0.0
- Chart-cairo-1.9.1
- cairo-0.13.8.0
- gtk2hs-buildtools-0.13.8.0
- git: git://github.com/hasktorch/pipes-text.git
  commit: 3dd3d9519306ea06f0c15ad71bdf57e1dfd0b747
# - show-prettyprint-0.3.0.1@sha256:c2c004bd77a1815b3d75a4cad1ec41a1b3f754ed259593414a195c4b19c02f16,1723

nix:
  packages: [zlib.dev, zlib.out]
