resolver: nightly-2017-09-20

packages:
- 'core'
- 'codegen'
- 'interface'
- 'tests'
- 'tools'

extra-deps: []

flags: {}

extra-package-dbs: []

# extra-include-dirs: ['vendor/torch7/lib/TH/', 'vendor/torch7/lib/TH/generic/']

# _must_ explicitly link TH dylib
extra-lib-dirs:
  - ./vendor/build/
ghc-options:
  "torch-core": -lTH
  "torch-codegen": -lTH
  "torch-tests": -lTH
  "torch-tools": -lTH

