resolver: lts-10.2

packages:
- 'codegen'
- 'raw/th'
- 'raw/thc'
- 'raw/tests'
- 'types/th'
- 'types/thc'
#- 'signatures/unsigned'
#- 'signatures/signed'
#- 'signatures/floating'
#- 'core'
#- 'core-indef-unsigned'
#- 'core-indef-signed'
#- 'core-indef-floating'
#- 'examples'
- location:
    git: https://github.com/austinvhuang/c2hsc.git
    commit: e31a2cb894faf4c0cf4a3af3058152149f2b2ee3
  extra-dep: true

extra-deps:
- dimensions-1.0.0.0
- numeric-limits-0.1.0.0

flags: {}

extra-package-dbs: []

extra-include-dirs: []

extra-lib-dirs:
- ./vendor/build
- /home/stites/.pyenv/versions/ai/lib/python3.6/site-packages/torch/lib

ghc-options:
  "hasktorch-raw-th": -lATen -lEHX
  "hasktorch-raw-thc": -lATen -lEHX
  # "hasktorch-core": -lATen -lEHX
  # "hasktorch-examples": -lATen -lEHX
  #"hasktorch-raw-types": -lATen -lEHX

# ghci-options for inline-c should include -fobject-code -O0
