resolver: nightly-2017-11-22

packages:
- 'codegen'
- 'core'
- 'examples'
- 'interface'
- 'nn'
- 'raw'
- 'tests'
- 'tools'
- location:
    git: https://github.com/austinvhuang/c2hsc.git
    commit: e31a2cb894faf4c0cf4a3af3058152149f2b2ee3
  extra-dep: true

extra-deps: []

flags: {}

extra-package-dbs: []

extra-include-dirs: ['vendor/bindings-dsl']
# extra-include-dirs: ['vendor/torch7/lib/TH/', 'vendor/torch7/lib/TH/generic/']

# _must_ explicitly link TH dylib
extra-lib-dirs: 
- ./vendor/build
- /Users/huanga13/projects-personal/hasktorch/vendor/build

ghc-options:
  "hasktorch-core": -lATen -lEHX
  "hasktorch-codegen": -lATen -lEHX
  "hasktorch-examples": -lATen -lEHX
  "hasktorch-nn": -lATen -lEHX
  "hasktorch-raw": -lATen -lEHX
  "hasktorch-tests": -lATen -lEHX
  "hasktorch-tools": -lATen -lEHX
  # "hasktorch-core": -lTH -lEHX
  # "hasktorch-codegen": -lTH -lEHX
  # "hasktorch-examples": -lTH -lEHX
  # "hasktorch-nn": -lTH -lEHX
  # "hasktorch-raw": -lTH -lEHX
  # "hasktorch-tests": -lTH -lEHX
  # "hasktorch-tools": -lTH -lEHX

# ghci-options for inline-c should include -fobject-code -O0
