resolver: lts-13.1

packages:
- codegen
- ffi
- inline-c/inline-c
- inline-c/inline-c-cpp


extra-include-dirs:
  - deps/libtorch/include/torch/csrc/api/include
  - deps/libtorch/include

extra-lib-dirs:
  - deps/libtorch/lib
  - deps/mklml/lib

# see https://github.com/commercialhaskell/stack/issues/4073
# with-gcc: /usr/local/bin/gcc-7