resolver: lts-13.1

packages:
- codegen
- ffi
- inline-c/inline-c
- inline-c/inline-c-cpp


extra-include-dirs:
  - deps/libtorch/include/torch/csrc/api/include
  - deps/libtorch/include

extra-lib-dirs:
  - deps/libtorch/lib
  - deps/mklml/lib

# see https://github.com/commercialhaskell/stack/issues/4073
# with-gcc: /usr/local/bin/gcc-7

extra-deps:
- fficxx-0.5.0.1@sha256:dd3638df82c2ce179f17e97f22068031ae0ba9aa75de9ed8a6b026c8088cc40c
- template-0.2.0.10@sha256:f822de4d34c45bc84b33a61bc112c15fedee6fa6dc414c62b10456395a868f85
