resolver: nightly-2017-10-20

packages:
- 'codegen'
- 'core'
- 'examples'
- 'interface'
- 'nn'
- 'raw'
- 'tests'
- 'tools'
- location:
    git: https://github.com/austinvhuang/c2hsc.git
    commit: e31a2cb894faf4c0cf4a3af3058152149f2b2ee3
  extra-dep: true

extra-deps: []

flags: {}

extra-package-dbs: []

extra-include-dirs: ['vendor/bindings-dsl']
# extra-include-dirs: ['vendor/torch7/lib/TH/', 'vendor/torch7/lib/TH/generic/']

# _must_ explicitly link TH dylib
extra-lib-dirs:
  - ./vendor/build/

ghc-options:
  "hasktorch-core": -lTH
  "hasktorch-codegen": -lTH
  "hasktorch-examples": -lTH
  "hasktorch-nn": -lTH
  "hasktorch-raw": -lTH
  "hasktorch-tests": -lTH
  "hasktorch-tools": -lTH
# ghci-options for inline-c should include -fobject-code -O0
