name: hasktorch-aten
version: '0.1.0.0'
synopsis: Torch for tensors and neural networks in Haskell
description: aten sublibrary
category: Tensors, Machine Learning
author: Austin Huang
license: BSD3
github: austinvhuang/hasktorch

dependencies:
- base >=4.7 && <5
- singletons >=2.2
- text >=1.2.2.2
- aeson-pretty >= 0.8.5
- aeson >= 1.1
- bytestring >= 0.10.8
- yaml >=0.8.25

library:
  source-dirs:
  - src
