version: 2

jobs:
  stack-build:
    docker:
      - image: "ubuntu:18.04"
    environment:
      LD_LIBRARY_PATH: /root/project/deps/libtorch/lib:/root/project/deps/mklml/lib
    steps:
      - run: echo $LD_LIBRARY_PATH
      - run: apt update -qq && apt install -y cmake wget unzip git libtinfo-dev python3 python3-yaml
      - run: update-alternatives --install /usr/bin/python python /usr/bin/python3 1
      - checkout
      - run: git submodule init && git submodule update
      - run: wget -qO- https://get.haskellstack.org/ | sh
      - run: gcc --version
      - run: stack --version
      - run: cd deps/ ; ./get-deps.sh USE_BINARY_FOR_CI
      - run: cd libtorch-test ; make
      - run:
          name: stack build
          command: stack build --jobs 2
          no_output_timeout: 15m
      - run: stack test --jobs 2
      - run: stack exec ffi-test
      - run: stack exec codegen-exe
      - run: stack test --jobs 2
      - run: stack exec ffi-test
  cabal-build:
    docker:
      - image: "ubuntu:18.04"
    environment:
      LD_LIBRARY_PATH: /root/project/deps/libtorch/lib:/root/project/deps/mklml/lib
      PATH: /opt/ghc/bin:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin
    steps:
      - run: echo $LD_LIBRARY_PATH
      - run: apt update -qq && apt install -y cmake curl wget unzip git libtinfo-dev python3 python3-yaml
      - run: apt -y --allow-downgrades --allow-remove-essential --allow-change-held-packages install locales software-properties-common apt-transport-https
      - run: add-apt-repository ppa:hvr/ghc
      - run: apt-get update -qq && apt-get -y --allow-downgrades --allow-remove-essential --allow-change-held-packages install build-essential zlib1g-dev liblapack-dev libblas-dev ghc-8.6.4 cabal-install-head devscripts debhelper python3-pip
      - run: update-alternatives --install /usr/bin/python python /usr/bin/python3 1
      - checkout
      - run: git submodule init && git submodule update
      - run: gcc --version
      - run: cabal --version
      - run: cd deps/ ; ./get-deps.sh USE_BINARY_FOR_CI
      - run: cd libtorch-test ; make
      - run: ./setup-cabal.sh
      - run: cabal new-update
      - run: cabal new-install hspec-discover
      - run:
          name: cabal new-build all
          command: cabal new-build all --jobs=2
          no_output_timeout: 15m
      - run: cabal new-test ffi --jobs=2
      - run: cabal new-exec ffi-test
      - run: cabal new-exec codegen-exe
      - run: cabal new-test ffi --jobs=2
      - run: cabal new-exec ffi-test
  osx-stack-build:
    macos:
      xcode: "10.2.1"
    environment:
      DYLD_LIBRARY_PATH: /Users/distiller/project/deps/libtorch/lib:/Users/distiller/project/deps/mklml/lib
      PATH: /Users/distiller/project/.local/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
    steps:
      - run: echo $LD_LIBRARY_PATH
      - checkout
      - run: git submodule init && git submodule update
      - run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      - run: brew install wget cmake libomp
      - run: brew install python
      - run: pip3 install pyyaml
      - run: mkdir -p .local/bin
      - run: rm /usr/local/bin/python
      - run: ln -s /usr/local/bin/python3 .local/bin/python
      - run: wget -qO- https://get.haskellstack.org/ | sh
      - run: clang --version
      - run: stack --version
      - run: cd deps/ ; ./get-deps.sh USE_BINARY_FOR_CI
      - run: cp -a deps/libtorch/lib/*.dylib deps/mklml/lib/*.dylib /usr/local/lib/
      - run: cd libtorch-test ; make
      - run:
          name: stack build
          command: stack build --jobs 2
          no_output_timeout: 15m
      - run: stack test --jobs 2
      - run: stack exec ffi-test
      - run: stack exec codegen-exe
      - run: stack test --jobs 2
      - run: stack exec ffi-test

workflows:
  version: 2
  build:
    jobs:
      - "stack-build"
      - "cabal-build"
      - "osx-stack-build"
