version: 2

global_defaults: &defaults
  machine: true
  PATH_ADDITIONS: /home/circleci/.local/bin

jobs:
  system-libraries:
    machine: true
    steps:
      - run: sudo apt-get update --fix-missing

  stack:
    machine: true
    steps:
      - run: wget -qO- https://get.haskellstack.org/ | sh

  build:
    machine: true
    steps:
      - run: echo 'export PATH=/home/circleci/.local/bin:$PATH' >> $BASH_ENV
      - run: gcc --version
      - run: stack --version
      - run: cd libtorch-test ; make
      - run: stack build
      - run: stack exec codegen
      - run: stack exec ffi



workflows:
  version: 2
  build:
    jobs:
      - stack
      - build:
          requires:
            - stack