version: 2

jobs:
  build:
    docker:
      - image: "ubuntu:18.04"
    environment:
      LD_LIBRARY_PATH: /root/project/deps/libtorch/lib:/root/project/deps/mklml/lib
    steps:
      - run: echo $LD_LIBRARY_PATH
      - run: apt update -qq && apt install -y cmake wget unzip git libtinfo-dev
      - checkout
      - run: git submodule init && git submodule update
      - run: wget -qO- https://get.haskellstack.org/ | sh
      - run: gcc --version
      - run: stack --version
      - run: cd libtorch-test ; make
      - run:
          name: stack build
          command: stack build --jobs 2
          no_output_timeout: 15m
      - run: stack test --jobs 2
      - run: stack exec codegen
      - run: stack exec ffi-test
