version: 2.0

dependencies:
  cache_directories:
    - "~/.stack"
  pre:
    - wget -qO- https://get.haskellstack.org/ | sh
  override:
    - stack setup

compile:
  override:
    - stack build

test:
  override:
    - stack test


