name:          hasktorch-raw-types
version:       0.0.1.0
synopsis:      Raw C-types from torch.
description:   core C types
github:        hasktorch/hasktorch
license:       BSD3
author:        Austin Huang

library:
  build-tools: c2hs
  dependencies:
    - base >= 4.7 && < 5
    - inline-c >= 0.5
  source-dirs: src

