name: cabal-linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup packages
      run: |
        sudo apt update -qq
        sudo apt -y --allow-downgrades --allow-remove-essential --allow-change-held-packages install locales software-properties-common apt-transport-https
        sudo add-apt-repository -y ppa:hvr/ghc
        sudo apt update -qq
        sudo apt -y --allow-downgrades --allow-remove-essential --allow-change-held-packages install build-essential zlib1g-dev liblapack-dev libblas-dev ghc-8.6.5 cabal-install-head devscripts debhelper python3-pip cmake curl wget unzip git libtinfo-dev python3 python3-yaml
        update-alternatives --install /usr/bin/python python /usr/bin/python3 1
    - name: Setup repos
      run: |
        git submodule init && git submodule update
    - name: Build
      run: |
        export PATH=/opt/ghc/bin:$PATH
        source setenv
        pushd deps/ ; ./get-deps.sh -a cpu -c; popd
        ./setup-cabal.sh
        cabal new-update
        cabal new-install hspec-discover
        cabal new-build all --jobs=2 --write-ghc-environment-files=always
    - name: Test
      run: |
        export PATH=/opt/ghc/bin:$PATH
        source setenv
        cabal new-test all --jobs=2 --write-ghc-environment-files=always
        cabal new-exec codegen-exe
        cabal exec xor_mlp
