name: nix-macos

on: [push, pull_request]

jobs:
  build-shell-cache:
    if: github.repository == 'hasktorch/hasktorch'
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v8
      - uses: cachix/cachix-action@v6
        with:
          name: hasktorch
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: cachix use iohk
      - run: nix-build shell.nix
  build-ci-cache:
    if: github.repository == 'hasktorch/hasktorch'
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v8
      - uses: cachix/cachix-action@v6
        with:
          name: hasktorch
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: cachix use iohk
      - run: nix-build
