name: nix-haddoc-linux
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v6
    - name: Setup repo
      run: |
        git submodule init && git submodule update
    - name: Build
      run: |
        cachix use hasktorch
        nix-build -A hasktorch-docs
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        # PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXTERNAL_REPOSITORY: hasktorch/hasktorch.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./result/share/doc
