name: nix-linux-cu9

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt -y purge ghc* cabal-install* php* || true
        sudo apt autoremove -y || true
        sudo apt autoclean -y || true
        docker rmi $(docker image ls -aq)
        df -h
    - uses: cachix/install-nix-action@v7
    - name: Setup repo
      run: |
        git submodule init && git submodule update
    - uses: cachix/cachix-action@releases/v5
      with:
        skipNixBuild: false
        name: hasktorch
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        nixBuildArgs: ./shared.nix -A defaultCuda92.hsPkgs.libtorch-ffi.components.all -A defaultCuda92.hsPkgs.hasktorch.components.all -A defaultCuda92.hsPkgs.examples.components.all -A defaultCuda92.hsPkgs.experimental.components.all
