name: nix-linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v7
    - name: Setup repo
      run: |
        git submodule init && git submodule update
    - uses: cachix/cachix-action@releases/v5
      with:
        skipNixBuild: false
        name: hasktorch
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        nixBuildArgs: -A hasktorch-codegen -A libtorch-ffi_cpu  -A hasktorch_cpu -A hasktorch-examples_cpu -A hasktorch-experimental_cpu
