name: nix-linux-cu9

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v7
    - name: Setup repo
      run: |
        git submodule init && git submodule update
    - uses: cachix/cachix-action@releases/v5
      with:
        skipNixBuild: false
        name: hasktorch
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        nixBuildArgs: |
          -A libtorch-ffi_cudatoolkit_9_2 \
          -A hasktorch_cudatoolkit_9_2 \
          -A hasktorch-examples_cudatoolkit_9_2 \
          -A hasktorch-experimental_cudatoolkit_9_2
