name: nix-jupyterlab

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v6
    - name: Setup repo
      run: |
        git submodule init && git submodule update
    - name: Build
      run: |
        nix-env -i cachix
        cachix use hasktorch
        cachix use jupyterwith
        cd experimental/jupyterlab
        nix-shell --command "echo"
