name: nix-macos

on: [push, pull_request]

jobs:
  tests:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v8
      - run: nix-env -iA cachix -f https://cachix.org/api/v1/install
      - run: cachix use iohk
      - run: |
          nix-build shared.nix -A defaultCpu.hsPkgs.libtorch-ffi.checks.spec
          nix-build shared.nix -A defaultCpu.hsPkgs.hasktorch.checks.spec
          nix-build shared.nix -A defaultCpu.hsPkgs.examples.checks.spec
  build-shell-cache:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v8
      - uses: cachix/cachix-action@v6
        with:
          name: hasktorch
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: cachix use iohk
      - run: nix-build shell.nix
  build-ci-cache:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v8
      - uses: cachix/cachix-action@v6
        with:
          name: hasktorch
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: cachix use iohk
      - run: nix-build
