name: nix-macos

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v3
    - name: Setup repo
      run: |
        git submodule init && git submodule update
    - name: Setup cachix
      run: |
        nix-env -iA cachix -f https://cachix.org/api/v1/install
    - name: Build
      run: |
        cachix use pytorch-world
        nix-build
