name: nix-macos

on: [push, pull_request]

jobs:
  tests:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
      - run: nix-env -iA cachix -f https://cachix.org/api/v1/install
      - run: cachix use iohk
      - run: |
          nix-build -A haskellPackages.libtorch-ffi.checks.spec
          nix-build -A haskellPackages.hasktorch.checks.spec
          nix-build -A haskellPackages.examples.checks.spec
  build-cache:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
      - uses: cachix/cachix-action@v6
        with:
          name: hasktorch
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: cachix use iohk
      - run: nix-build
